### ISSUE TITLE
Bill search does not "remember" the search term used in main search

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/legacy-openstates.org#66]
Example flow:

1. On the homepage, search a term in the header's search box
2. On the search results page, click the `View all bill results` button
3. The bill-search page will come up, but it won't remember what the search term was (ie, it'll display all bills for the country, unfiltered, and the `Search text` field on the left side panel will not contain the original search term)

**Comment by jamesturk** [comment]
dupe of #56
